// <auto-generated />
using System;
using FinalProject_Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_WebApp.Migrations
{
    [DbContext(typeof(RepositoryContex))]
    [Migration("20250115230040_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProject_Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 976, DateTimeKind.Local).AddTicks(8658),
                            Name = "Book",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 976, DateTimeKind.Local).AddTicks(8668),
                            Name = "Computer",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 976, DateTimeKind.Local).AddTicks(8669),
                            Name = "Phone",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(615),
                            Name = "Baby",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(925),
                            Name = "Music",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(936),
                            Name = "Outdoors & Shoes",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(969),
                            Name = "Games, Beauty & Clothing",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(992),
                            Name = "Grocery, Home & Kids",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1011),
                            Name = "Sports",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1020),
                            Name = "Health, Kids & Home",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1037),
                            Name = "Games & Automotive",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1051),
                            Name = "Automotive",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1058),
                            Name = "Automotive & Garden",
                            Status = 0
                        });
                });

            modelBuilder.Entity("FinalProject_Entities.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ShowCase")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1917),
                            ImageUrl = "default.png",
                            Name = "Istanbul",
                            Price = 35m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1924),
                            ImageUrl = "default.png",
                            Name = "Fatih",
                            Price = 35m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1925),
                            ImageUrl = "default.png",
                            Name = "Asus Pc",
                            Price = 35000m,
                            ShowCase = false,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1927),
                            ImageUrl = "default.png",
                            Name = "Lenovo Pc",
                            Price = 38000m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1928),
                            ImageUrl = "default.png",
                            Name = "Mac Book",
                            Price = 65000m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1931),
                            ImageUrl = "default.png",
                            Name = "HP Pc",
                            Price = 65000m,
                            ShowCase = false,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1932),
                            ImageUrl = "default.png",
                            Name = "Roman",
                            Price = 45m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1933),
                            ImageUrl = "default.png",
                            Name = "Iphone 16 Pro Max",
                            Price = 99000m,
                            ShowCase = false,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1935),
                            ImageUrl = "default.png",
                            Name = "Iphone 15 Pro Max",
                            Price = 85000m,
                            ShowCase = false,
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 979, DateTimeKind.Local).AddTicks(1937),
                            ImageUrl = "default.png",
                            Name = "Samsung",
                            Price = 65000m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 13,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4020),
                            ImageUrl = "default.png",
                            Name = "Tasty Frozen Car",
                            Price = 65404.10m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4724),
                            ImageUrl = "default.png",
                            Name = "Generic Steel Chicken",
                            Price = 22477.45m,
                            ShowCase = false,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4768),
                            ImageUrl = "default.png",
                            Name = "Awesome Steel Soap",
                            Price = 62743.89m,
                            ShowCase = false,
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4795),
                            ImageUrl = "default.png",
                            Name = "Fantastic Wooden Pants",
                            Price = 77401.11m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4893),
                            ImageUrl = "default.png",
                            Name = "Refined Frozen Bacon",
                            Price = 75952.55m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4920),
                            ImageUrl = "default.png",
                            Name = "Refined Fresh Soap",
                            Price = 68719.45m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4946),
                            ImageUrl = "default.png",
                            Name = "Awesome Granite Shirt",
                            Price = 26964.25m,
                            ShowCase = true,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4972),
                            ImageUrl = "default.png",
                            Name = "Handcrafted Cotton Shirt",
                            Price = 43962.45m,
                            ShowCase = false,
                            Status = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(4999),
                            ImageUrl = "default.png",
                            Name = "Tasty Soft Cheese",
                            Price = 82596.75m,
                            ShowCase = false,
                            Status = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 1, 16, 2, 0, 39, 981, DateTimeKind.Local).AddTicks(5027),
                            ImageUrl = "default.png",
                            Name = "Tasty Concrete Sausages",
                            Price = 78849.71m,
                            ShowCase = false,
                            Status = 0
                        });
                });

            modelBuilder.Entity("FinalProject_Entities.Models.Product", b =>
                {
                    b.HasOne("FinalProject_Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinalProject_Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
